Error label
Project-U-Development/refund-tracker.github.io pull request #64
Opened 2023-01-06 20:27 UTC by NatalyKokidko

2023-01-09 14:46 UTC, svetikzp reviewed
Plug in css:
@import "./button/button.css";
@import "./typography/typography.css";
@import "./typography/color.css"

2023-01-09 14:47 UTC, svetikzp commented
Plug in css:
https://github.com/import "./button/button.css";
https://github.com/import "./typography/typography.css";
https://github.com/import "./typography/color.css"

2023-01-12 19:40 UTC, TatianaBortnik requested changes

2023-01-12 19:40 UTC, TatianaBortnik commented on client/components/errorLabel/errorLabel.css
> -.button-error {
You should import typography.css to use font-family by default.
The label now displayed in Times New Roman despite the correct font is specified.
In typography.css defined class error-message. Use it

2023-01-12 19:40 UTC, TatianaBortnik commented on client/components/errorLabel/errorLabel.css
> +.error {
You should use color variables defined in color.css instead of color codes.
If the desired color is missing, you must add it in color.css

2023-01-12 19:40 UTC, TatianaBortnik commented on client/components/errorLabel/errorLabel.css
>      align-items: center;
Label text is not centered

2023-01-21 11:34 UTC, tbazko requested changes
You already have similar code in another PR. Is that a mistake or done or purpose?

2023-01-21 11:34 UTC, tbazko commented on client/components/errorLabel/errorLabel.html
> +<error-label id="label_error" class="error-message">Error</error-label>
This is not valid HTML tag. It does not exist.

2023-01-31 18:20 UTC, merged