add filter button
Project-U-Development/refund-tracker.github.io pull request #68
Opened 2023-01-07 14:26 UTC by NatalyKokidko

2023-01-09 15:04 UTC, svetikzp commented
Everything is fine, just plug in the styles css.

2023-01-13 07:57 UTC, TatianaBortnik commented on client/components/filterButton/filterButton.html
> +<link rel="stylesheet" href="./filterButton.css">
You should copy html from **button** component

2023-01-13 07:57 UTC, TatianaBortnik commented on client/components/filterButton/filterButton.css
> +.filter-btn {
You should import button.css

2023-01-13 07:58 UTC, TatianaBortnik requested changes
You shoul import button.css

2023-01-21 11:41 UTC, tbazko requested changes
I'm afraid task was not well refined actually.
You don't need implement design of the button. That is already done within Button component. You needed to make "filtering" UI which should be opened when you click on Filter button. 

There are some designs here, but I'm not sure they fit our purpose. https://www.figma.com/file/lK8ZJBtGidUgLojOiDNkYn/Refund-tracker?node-id=3118%3A359&t=hW64SCszmWr5FwSj-0

@NatalyKokidko I suggest we make this component together. What do you think?

2023-01-21 14:10 UTC, NatalyKokidko commented
With pleasure, thanks for your help.

2023-01-23 17:31 UTC, closed without merging