Log in page
Project-U-Development/refund-tracker.github.io pull request #69
Opened 2023-01-09 19:51 UTC by vikawal

This is pull-request mainly about log-in page, but also NAME field from register page was deleted. Please, check it. Especially JS part =-))

2023-01-12 19:03 UTC, TatianaBortnik requested changes

2023-01-12 19:03 UTC, TatianaBortnik commented on client/components/pageLogIn/logIn.mjs
> +// import { inputListener } from '../input/input.mjs';
All commented code should be deleted

2023-01-13 10:50 UTC, vikawal commented on client/components/pageLogIn/logIn.mjs
> +// import { inputListener } from '../input/input.mjs';
Ok.Done

2023-01-23 18:15 UTC, tbazko approved these changes

2023-01-24 11:15 UTC, vikawal commented
should I merge it or wait for second approval?

2023-01-26 17:21 UTC, anynikulina approved these changes

2023-01-26 17:23 UTC, merged