Butsearch
Project-U-Development/refund-tracker.github.io pull request #72
Opened 2023-01-11 15:48 UTC by svetikzp

2023-01-12 14:27 UTC, magnicel commented
JS needs to be added

2023-01-13 09:24 UTC, TatianaBortnik requested changes

2023-01-13 09:24 UTC, TatianaBortnik commented on client/components/search/search.css
> +.search-form-btn {
image on search button does not match Figma and does not centered 
![image](https://user-images.githubusercontent.com/10188652/212284701-abc616bb-315a-480c-8b1a-666010769804.png)

2023-01-13 09:24 UTC, TatianaBortnik commented on client/components/search/search.css
> +.search-form {
Search design does not match Figma.
You should use typography

2023-01-26 18:23 UTC, anynikulina approved these changes

2023-01-26 18:25 UTC, merged